/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PlacePlaceIdRouteImport } from './routes/place.$placeId'
import { Route as PlacePlaceIdIndexRouteImport } from './routes/place.$placeId.index'
import { Route as PlacePlaceIdOutlookRouteImport } from './routes/place.$placeId.outlook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdIndexRoute = PlacePlaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlacePlaceIdRoute,
} as any)
const PlacePlaceIdOutlookRoute = PlacePlaceIdOutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => PlacePlaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/place/$placeId': typeof PlacePlaceIdRouteWithChildren
  '/place/$placeId/outlook': typeof PlacePlaceIdOutlookRoute
  '/place/$placeId/': typeof PlacePlaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/place/$placeId/outlook': typeof PlacePlaceIdOutlookRoute
  '/place/$placeId': typeof PlacePlaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/place/$placeId': typeof PlacePlaceIdRouteWithChildren
  '/place/$placeId/outlook': typeof PlacePlaceIdOutlookRoute
  '/place/$placeId/': typeof PlacePlaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saved'
    | '/place/$placeId'
    | '/place/$placeId/outlook'
    | '/place/$placeId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/saved' | '/place/$placeId/outlook' | '/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/saved'
    | '/place/$placeId'
    | '/place/$placeId/outlook'
    | '/place/$placeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedRoute: typeof SavedRoute
  PlacePlaceIdRoute: typeof PlacePlaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId/': {
      id: '/place/$placeId/'
      path: '/'
      fullPath: '/place/$placeId/'
      preLoaderRoute: typeof PlacePlaceIdIndexRouteImport
      parentRoute: typeof PlacePlaceIdRoute
    }
    '/place/$placeId/outlook': {
      id: '/place/$placeId/outlook'
      path: '/outlook'
      fullPath: '/place/$placeId/outlook'
      preLoaderRoute: typeof PlacePlaceIdOutlookRouteImport
      parentRoute: typeof PlacePlaceIdRoute
    }
  }
}

interface PlacePlaceIdRouteChildren {
  PlacePlaceIdOutlookRoute: typeof PlacePlaceIdOutlookRoute
  PlacePlaceIdIndexRoute: typeof PlacePlaceIdIndexRoute
}

const PlacePlaceIdRouteChildren: PlacePlaceIdRouteChildren = {
  PlacePlaceIdOutlookRoute: PlacePlaceIdOutlookRoute,
  PlacePlaceIdIndexRoute: PlacePlaceIdIndexRoute,
}

const PlacePlaceIdRouteWithChildren = PlacePlaceIdRoute._addFileChildren(
  PlacePlaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedRoute: SavedRoute,
  PlacePlaceIdRoute: PlacePlaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
